contact_links:
  - name: 💬 Official Telegram Group
    url: https://t.me/PocoF3GlobalOfficial
    about: "@PocoF3GlobalOfficial"
  - name: 💬 Official Telegram Channel
    url: https://t.me/pocoF3GlobalUpdates
    about: "@PocoF3GlobalUpdates"