contact_links:
  - name: 💬 Official Telegram Group - @PocoF3GlobalOfficial
    url: https://t.me/PocoF3GlobalOfficial
  - name: 💬 Official Telegram Channel - @PocoF3GlobalUpdates
    url: https://t.me/pocoF3GlobalUpdates